apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: regapp.yml
spec:
  selector:
    app: regapp.yml 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
